### ISSUE TITLE
rets_client.get_lookup_values fails with lookup_name=*

### ISSUE THREAD

**Issue by briandking** [refindlyllc/rets#199]
Making a call like:
 rets_client.get_lookup_values('Property', '*')

Fails with:

```
Traceback (most recent call last):
  File "/apps/MLS/py37-venv/lib/python3.7/site-packages/rets/session.py", line 228, in _make_metadata_request
    return parser.parse(response=response, metadata_type=metadata_type)
  File "/apps/MLS/py37-venv/lib/python3.7/site-packages/rets/parsers/metadata.py", line 22, in parse
    self.analyze_reply_code(xml_response_dict=xml)
  File "/apps/MLS/py37-venv/lib/python3.7/site-packages/rets/parsers/base.py", line 55, in analyze_reply_code
    raise RETSException(reply_text, reply_code)
rets.exceptions.RETSException: Invalid Format

```
A packet capture shows the RETS server is actually returning the data, so the client is just not handing it.
Debug logging shows:

```
2019-02-25 11:59:07,301: DEBUG   : urllib3.connectionpool: http://rets.nbrun.mlxmatrix.com:80 "POST /rets/GetMetadata.ashx HTTP/1.1" 200 195
2019-02-25 11:59:07,305: DEBUG   : rets: Received ReplyCode of 20513 from the RETS Server: 20513
2019-02-25 11:59:07,420: DEBUG   : urllib3.connectionpool: http://rets.nbrun.mlxmatrix.com:80 "POST /rets/GetMetadata.ashx HTTP/1.1" 200 None
2019-02-25 11:59:07,711: DEBUG   : rets: Received ReplyCode of 0 from the RETS Server: 0
```

The expectation is that it would be a dictionary of dictionaries that is returned.

**Comment by mcrowson** [comment]
Can you get the XML it is returning and share that?

**Comment by briandking** [comment]
Attached XML as GetMetadata.ashx.xml.txt

[GetMetadata.ashx.xml.txt](https://github.com/refindlyllc/rets/files/2902567/GetMetadata.ashx.xml.txt)
